"""add approval approvers column for l3 quorum

Revision ID: 24413e374e1c
Revises: 426bf65ff049
Create Date: 2026-08-27 10:58:58.085980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24413e374e1c"
down_revision: Union[str, Sequence[str], None] = "426bf65ff049"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # R-P2/#7: server_default backfills existing approval_requests rows with the
    # empty string (matching the ORM default="") so a NOT NULL add succeeds on a
    # populated table. Without it, SQLite/PG reject the add on any non-empty
    # approval_requests.
    op.add_column(
        "approval_requests",
        sa.Column("approvers", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("approval_requests", "approvers")
    # ### end Alembic commands ###
