"""add hot-path indexes p0_2

Revision ID: 426bf65ff049
Revises: 7e8a9f01b2c4
Create Date: 2026-08-26 12:09:47.000225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "426bf65ff049"
down_revision: Union[str, Sequence[str], None] = "7e8a9f01b2c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=False)
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"], unique=False)
    op.create_index("ix_approval_requests_model_id", "approval_requests", ["model_id"], unique=False)
    op.create_index("ix_approval_requests_status", "approval_requests", ["status"], unique=False)
    op.create_index("ix_approval_requests_tenant_id", "approval_requests", ["tenant_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_tenant_id", "audit_logs", ["tenant_id"], unique=False)
    op.create_index("ix_cluster_nodes_status", "cluster_nodes", ["status"], unique=False)
    op.create_index("ix_deployments_model_id", "deployments", ["model_id"], unique=False)
    op.create_index("ix_deployments_status", "deployments", ["status"], unique=False)
    op.create_index("ix_deployments_tenant_id", "deployments", ["tenant_id"], unique=False)
    op.create_index("ix_distributed_tasks_status", "distributed_tasks", ["status"], unique=False)
    op.create_index("ix_download_tasks_model_id", "download_tasks", ["model_id"], unique=False)
    op.create_index("ix_download_tasks_status", "download_tasks", ["status"], unique=False)
    op.create_index("ix_evaluation_results_model_id", "evaluation_results", ["model_id"], unique=False)
    op.create_index("ix_evaluation_results_tenant_id", "evaluation_results", ["tenant_id"], unique=False)
    op.create_index("ix_gitlfs_locks_model_id", "gitlfs_locks", ["model_id"], unique=False)
    op.create_index("ix_lora_merge_tasks_status", "lora_merge_tasks", ["status"], unique=False)
    op.create_index("ix_model_branches_model_id", "model_branches", ["model_id"], unique=False)
    op.create_index("ix_model_branches_status", "model_branches", ["status"], unique=False)
    op.create_index("ix_model_favorites_model_id", "model_favorites", ["model_id"], unique=False)
    op.create_index("ix_model_ratings_model_id", "model_ratings", ["model_id"], unique=False)
    op.create_index("ix_model_tags_model_id", "model_tags", ["model_id"], unique=False)
    op.create_index("ix_model_versions_created_at", "model_versions", ["created_at"], unique=False)
    op.create_index("ix_model_versions_model_id", "model_versions", ["model_id"], unique=False)
    op.create_index("ix_model_versions_status", "model_versions", ["status"], unique=False)
    op.create_index("ix_models_base_model_id", "models", ["base_model_id"], unique=False)
    op.create_index("ix_models_created_at", "models", ["created_at"], unique=False)
    op.create_index("ix_models_model_status", "models", ["model_status"], unique=False)
    op.create_index("ix_models_model_type", "models", ["model_type"], unique=False)
    op.create_index("ix_models_tenant_id", "models", ["tenant_id"], unique=False)
    op.create_index("ix_models_updated_at", "models", ["updated_at"], unique=False)
    op.create_index("ix_quantize_tasks_created_at", "quantize_tasks", ["created_at"], unique=False)
    op.create_index("ix_quantize_tasks_status", "quantize_tasks", ["status"], unique=False)
    op.create_index("ix_security_scans_model_id", "security_scans", ["model_id"], unique=False)
    op.create_index("ix_security_scans_status", "security_scans", ["status"], unique=False)
    op.create_index("ix_watermarks_model_id", "watermarks", ["model_id"], unique=False)
    op.create_index("ix_webhooks_is_active", "webhooks", ["is_active"], unique=False)
    op.create_index("ix_webhooks_tenant_id", "webhooks", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhooks_tenant_id", table_name="webhooks")
    op.drop_index("ix_webhooks_is_active", table_name="webhooks")
    op.drop_index("ix_watermarks_model_id", table_name="watermarks")
    op.drop_index("ix_security_scans_status", table_name="security_scans")
    op.drop_index("ix_security_scans_model_id", table_name="security_scans")
    op.drop_index("ix_quantize_tasks_status", table_name="quantize_tasks")
    op.drop_index("ix_quantize_tasks_created_at", table_name="quantize_tasks")
    op.drop_index("ix_models_updated_at", table_name="models")
    op.drop_index("ix_models_tenant_id", table_name="models")
    op.drop_index("ix_models_model_type", table_name="models")
    op.drop_index("ix_models_model_status", table_name="models")
    op.drop_index("ix_models_created_at", table_name="models")
    op.drop_index("ix_models_base_model_id", table_name="models")
    op.drop_index("ix_model_versions_status", table_name="model_versions")
    op.drop_index("ix_model_versions_model_id", table_name="model_versions")
    op.drop_index("ix_model_versions_created_at", table_name="model_versions")
    op.drop_index("ix_model_tags_model_id", table_name="model_tags")
    op.drop_index("ix_model_ratings_model_id", table_name="model_ratings")
    op.drop_index("ix_model_favorites_model_id", table_name="model_favorites")
    op.drop_index("ix_model_branches_status", table_name="model_branches")
    op.drop_index("ix_model_branches_model_id", table_name="model_branches")
    op.drop_index("ix_lora_merge_tasks_status", table_name="lora_merge_tasks")
    op.drop_index("ix_gitlfs_locks_model_id", table_name="gitlfs_locks")
    op.drop_index("ix_evaluation_results_tenant_id", table_name="evaluation_results")
    op.drop_index("ix_evaluation_results_model_id", table_name="evaluation_results")
    op.drop_index("ix_download_tasks_status", table_name="download_tasks")
    op.drop_index("ix_download_tasks_model_id", table_name="download_tasks")
    op.drop_index("ix_distributed_tasks_status", table_name="distributed_tasks")
    op.drop_index("ix_deployments_tenant_id", table_name="deployments")
    op.drop_index("ix_deployments_status", table_name="deployments")
    op.drop_index("ix_deployments_model_id", table_name="deployments")
    op.drop_index("ix_cluster_nodes_status", table_name="cluster_nodes")
    op.drop_index("ix_audit_logs_tenant_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_approval_requests_tenant_id", table_name="approval_requests")
    op.drop_index("ix_approval_requests_status", table_name="approval_requests")
    op.drop_index("ix_approval_requests_model_id", table_name="approval_requests")
    op.drop_index("ix_api_keys_tenant_id", table_name="api_keys")
    op.drop_index("ix_api_keys_key_hash", table_name="api_keys")
    # ### end Alembic commands ###
