"""add_ratings_favorites_branches_and_compliance_fields

Revision ID: 4a71a09a8f21
Revises: 834d0995bde8
Create Date: 2026-07-26 20:53:19.711974

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a71a09a8f21'
down_revision: str | Sequence[str] | None = '834d0995bde8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlfs_locks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_favorites',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_ratings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='approvallevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributed_tasks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('target_nodes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='distributedtaskstatus'), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('benchmark_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='evaluationstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lora_merge_tasks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('base_version_id', sa.String(length=16), nullable=False),
    sa.Column('lora_version_id', sa.String(length=16), nullable=False),
    sa.Column('target_format', sa.String(length=32), nullable=False),
    sa.Column('quant_bits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('output_version_id', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['lora_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_branches',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_version_id', sa.String(length=16), nullable=False),
    sa.Column('head_version_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MERGED', 'ARCHIVED', name='branchstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['head_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_scans',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watermarks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('watermark_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model_versions', sa.Column('encrypted', sa.Boolean(), nullable=False))
    op.add_column('model_versions', sa.Column('license_type', sa.String(length=64), nullable=False))
    op.add_column('model_versions', sa.Column('data_compliance', sa.Text(), nullable=False))
    op.add_column('quantize_tasks', sa.Column('calibration_dataset', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quantize_tasks', 'calibration_dataset')
    op.drop_column('model_versions', 'data_compliance')
    op.drop_column('model_versions', 'license_type')
    op.drop_column('model_versions', 'encrypted')
    op.drop_table('watermarks')
    op.drop_table('security_scans')
    op.drop_table('model_branches')
    op.drop_table('lora_merge_tasks')
    op.drop_table('evaluation_results')
    op.drop_table('distributed_tasks')
    op.drop_table('approval_requests')
    op.drop_table('model_ratings')
    op.drop_table('model_favorites')
    op.drop_table('gitlfs_locks')
    # ### end Alembic commands ###
