"""initial_schema

Revision ID: 834d0995bde8
Revises: 
Create Date: 2026-07-26 16:08:15.326958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834d0995bde8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_nodes',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capabilities', sa.String(length=256), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=16), nullable=False),
    sa.Column('api_key_id', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_type', sa.Enum('LLM', 'CHAT', 'EMBEDDING', 'MULTIMODAL', 'LORA', 'CODE', 'AUDIO', 'IMAGE', name='modeltype'), nullable=False),
    sa.Column('architecture', sa.String(length=64), nullable=False),
    sa.Column('params_size', sa.String(length=16), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('task_types', sa.String(length=256), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('hf_repo', sa.String(length=256), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_tags',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('format', sa.Enum('MLX', 'SAFETENSORS', 'GGUF', 'PYTORCH', 'ONNX', name='modelformat'), nullable=False),
    sa.Column('quantization', sa.Enum('FP32', 'FP16', 'BF16', 'Q8', 'Q6', 'Q4', 'Q2', 'NONE', name='quantization'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TESTING', 'PUBLISHED', 'DEPRECATED', 'RETIRED', name='versionstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('benchmark_score', sa.Float(), nullable=False),
    sa.Column('inference_latency', sa.Float(), nullable=False),
    sa.Column('throughput', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('successor_version_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'STOPPED', 'FAILED', name='deploymentstatus'), nullable=False),
    sa.Column('gray_enabled', sa.Boolean(), nullable=False),
    sa.Column('gray_version_id', sa.String(length=16), nullable=False),
    sa.Column('gray_traffic_ratio', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantize_tasks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('source_version_id', sa.String(length=16), nullable=False),
    sa.Column('target_format', sa.String(length=32), nullable=False),
    sa.Column('quant_bits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('output_version_id', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantize_tasks')
    op.drop_table('deployments')
    op.drop_table('model_versions')
    op.drop_table('model_tags')
    op.drop_table('webhooks')
    op.drop_table('models')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    op.drop_table('cluster_nodes')
    # ### end Alembic commands ###
