apiVersion: v1
kind: Service
metadata:
    name: {{ include "fusion-model-hub.fullname" . }}
    labels:
        app: {{ include "fusion-model-hub.name" . }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: 11444
          protocol: TCP
    selector:
        app: {{ include "fusion-model-hub.name" . }}
